lib = File.expand_path('../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require 'rake'
require 'rake/testtask'
require 'datastructures'

desc 'Runs Unit tests'
Rake::TestTask.new(:test) do |test|
  test.libs << 'lib' << 'test'
  test.pattern = 'test/**/*_test.rb'
  test.verbose = true
end

task :default => :test

desc 'Builds the gem'
task :build do
  sh "gem build datastructures.gemspec"
end

desc 'Builds and installs the gem'
task :install => :build do
  sh "gem install datastructures-#{DataStructures::VERSION}"
end